### ISSUE TITLE
kubesphere3.0  UnauthorizedError: Not Login

### ISSUE THREAD

**Issue by hidao** [kubesphere/website#244]
kubectl logs ks-console-b4df86d6f-xdgz8 -n kubesphere-system -f --tail=10
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  --> GET / 302 2ms 43b 2020/09/08T02:34:07.984
  <-- GET /login 2020/09/08T02:34:07.984
  -x- GET /login 200 12ms 14.82kb 2020/09/08T02:34:07.996

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92427499-2d82b180-f17c-11ea-9e8e-72d7e3061778.png)

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92427642-85b9b380-f17c-11ea-8d71-da46cbdb1fc6.png)

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92427806-ffea3800-f17c-11ea-8ef1-2c7efb101e2c.png)

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92428042-a7676a80-f17d-11ea-9c6b-79f8ce851aec.png)

**Comment by min-zh** [comment]
fixed by https://github.com/kubesphere/kubesphere/pull/2976
